### ISSUE TITLE
App Error: GET queue/jobs?limit=10000 => Allowed memory exhausted 

### ISSUE THREAD

**Issue by kacurez** [keboola/syrup-queue#88] opened 2019-02-04 09:45 UTC
volanie GET /queue/jobs?since=2018-10-01&until=2019-02-04&include=metrics&limit=10000
spadne ma app error 
Allowed memory size of 536870912 bytes exhausted (tried to allocate 41209078 bytes)

dovodom je prilis velky limit stranky resultu api callu. Imho riesenim je ho limitovat tj povolit len napr max limit=1000 a limit nad skonci ako user error.
https://papertrailapp.com/systems/kbc-us-east-1-syrup-api-i-0c4af260ddfcd4491/events?focus=1028940489979740163&selected=1028940489979740163

**Comment by odinuv** [comment] 2019-02-04 09:47
duplicate of https://github.com/keboola/syrup-queue/issues/85

**Closed** 2019-02-04 09:57 UTC
